# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170312_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
    ]
